### ISSUE TITLE
Database Schema change for School Filtering 

### ISSUE THREAD

**Issue by leechongyan** [leechongyan/Studtor_backend#30]
Frontend would need to filter by schools then by faculties. 

I suggest creating 2 tables instead of the current school table. One table is the school table and the other is the faculty table. Faculty is linked by both schools and courses. A school can have multiple faculties, and one faculty can have multiple courses. 

You need to return for example for the GetSchools method. 

A list of SchoolsDetails object of 
```
ID          int
Institution string
SchoolCode  string
SchoolName  string
FacultiesCode []string
Faculties Names []string
```

For courses, 

I need you to return 

```
type CourseWithSize struct {
	ID          int
	CourseCode  string
	CourseName  string
	TutorSize   int
	StudentSize int
        FacultyCode string
}
```

This will then allow the frontend to filter by clicking on school, which will then show a list of faculty code, which can then be used to filter the courses, hence the field of FacultyCode is needed for CourseWithSize object.

**Comment by leechongyan** [comment]
I will return this to chin when he gets the filtering field
```
[
    {
        "ID": 1,
        "SchoolCode": "NTU",
        "SchoolName": "Nanyang Technological University",
        "FacultyCodes": [
            "SCSE",
            "NBS",
            "NIE"
        ],
        "FacultyNames": [
            "Computer Science",
            "Business School",
            "Education"
        ]
    },
        {
        "ID": 2,
        "SchoolCode": "NUS",
        "SchoolName": "National University Singapore",
        "FacultyCodes": [
            "CS",
            "BIZ",
            "EDU"
        ],
        "FacultyNames": [
            "Computer Science",
            "Business School",
            "Education"
        ]
    }
]
```

**Comment by Jordan396** [comment]
Thanks for the suggestion. I would like to consider another alternative, which is to add columns for your `FacultyCode` and `FacultyName` to the schools table below.

![issue_30](https://user-images.githubusercontent.com/26784893/120060948-41b16a80-c08d-11eb-8601-af1e431d137a.png)

In other words, the current school table will represent both the school table and the faculty table. I understand that this would not satisfy [normalization](https://en.wikipedia.org/wiki/Database_normalization) rules, but since we're only supporting 2 schools (NTU and NUS) currently, it might not be necessary to separate the school and faculty table at this current stage.

@leechongyan thoughts?

**Comment by leechongyan** [comment]
sounds gd

**Comment by leechongyan** [comment]
resolved
